---

- hosts: jboss_eap_rhel_hosts
  become_user: "{{ ansible_rhel_user }}"
  become: true
  gather_facts: true

  tasks:
  - name: Install Java
    action: "{{ ansible_pkg_mgr }} name={{ jboss_java_pkg_name }} state=latest"
    when: install_java|bool
    tags:
    - common

  - name: Install Unzip
    action: "{{ ansible_pkg_mgr }} name=unzip state=latest"
    tags:
    - common

  - name: Set JBoss EAP Download Facts
    set_fact:
      #jboss_eap_artifact_url: "{{ jboss_eap_artifact_source }}"
      jboss_eap_artifact_dl_dest: "{{ '/tmp/' + jboss_eap_artifact_name }}"
      jboss_eap_library_dest: "/opt/{{ jboss_eap_user }}"
      #jboss_eap_patch_artifact_url: "{{ jboss_eap_patch_artifact_source }}"
      jboss_eap_patch_dest: "/tmp/{{ jboss_eap_patch_artifact_name }}"
    tags:
      - jboss_eap

  - name: Set JBoss EAP Group Facts
    set_fact:
      jboss_eap_group: "{{ jboss_eap_user }}"
    tags:
      - jboss_eap

  - name: Set JBoss EAP Service Directories Facts
    set_fact:
      jboss_eap_home: "{{ jboss_eap_library_dest }}/jboss-eap-{{jboss_eap_base_version}}"
      jboss_eap_service_conf_dir: "/etc/{{ (jboss_eap_base_version | version_compare('7.0','<')) | ternary(jboss_eap_user,'default')}}"
      jboss_eap_service_log_dir: "/var/log/{{ jboss_eap_user }}"
      jboss_eap_service_data_dir: "/var/run/{{ jboss_eap_user }}"
    tags:
      - jboss_eap

  - name: Set JBoss EAP Service Files Facts
    set_fact:
      jboss_eap_service_conf_file: "{{ jboss_eap_service_conf_dir }}/{{ (jboss_eap_base_version | version_compare('7.0','<')) | ternary('jboss-as.conf','jboss-eap.conf')}}"
      jboss_eap_bin_dir: "{{ jboss_eap_home }}/bin"
      jboss_eap_runtime_conf_file: "{{ jboss_eap_home }}/bin/standalone.conf"
      jboss_eap_service_file: "{{ (jboss_eap_base_version | version_compare('7.0','<')) | ternary('jboss-as-'+jboss_eap_mode+'.sh','jboss-eap-rhel.sh')}}"
    tags:
      - jboss_eap

  - name: Checking (jboss_eap_service_file) variable value.
    debug:
      var: "{{jboss_eap_service_file}}"
    tags:
      - testing

  - name: Set JBoss EAP Service Name EL 6
    set_fact:
      jboss_eap_service_name: "{{jboss_eap_service_file | splitext | first }}"
    tags:
      - jboss_eap

  - name: Create JBoss EAP Group
    group:
      name: "{{ jboss_eap_group }}"
      system: yes
      state: present
      gid: "400"
    tags:
      - jboss_eap

  - name: Create JBoss EAP User
    user:
      name: "{{ jboss_eap_user }}"
      comment: "JBoss EAP User"
      uid: "400"
      group: "{{ jboss_eap_group }}"
      home: "{{ jboss_eap_library_dest }}"
      shell: "/bin/bash"
    tags:
      - jboss_eap

  - name: Create JBoss EAP Library Destination
    become: true
    file:
      path: "{{ jboss_eap_library_dest }}"
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      state: directory
      mode: "755"
    tags:
      - jboss_eap

  - name: Create JBoss EAP Service Conf Directory
    file:
      path: "{{ jboss_eap_service_conf_dir }}"
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      state: directory
      mode: "755"
    tags:
      - jboss_eap

  - name: Copy JBoss EAP Service Conf File
    template:
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      src: jboss-as.conf.j2
      dest: "{{ jboss_eap_service_conf_file }}"
      backup: yes
      mode: "755"
    tags:
      - jboss_eap

  - name: Create JBoss EAP Service Log Directory
    file:
      path: "{{ jboss_eap_service_log_dir }}"
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      state: directory
      mode: "755"
    tags:
      - jboss_eap

  - name: Create JBoss EAP Service Runtime Data Directory
    file:
      path: "{{ jboss_eap_service_data_dir }}"
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      state: directory
      mode: "755"
    tags:
      - jboss_eap

  - name: Check Existence of Libraries
    become: true
    stat:
      path: "{{ jboss_eap_library_dest + '/jboss-eap-6.4/version.txt'}}"
    register: jboss_eap_exists
    tags:
      - jboss_eap

  - name: Determine if the Patch Can Be Applied
    become_user: "{{ jboss_eap_user }}"
    command: "{{ jboss_eap_home }}/bin/jboss-cli.sh 'patch info --verbose'"
    register: patch_info_result
    tags:
      - jboss_eap
      - dev
    when: jboss_eap_apply_patch == true and jboss_eap_exists.stat.exists == true

  - name: Copy JBoss EAP
    copy:
      src: "{{ jboss_eap_artifact_name }}"
      dest: "{{ jboss_eap_artifact_dl_dest }}"
    tags:
      - jboss_eap
    when: transfer_method == 'copy-from-controller' and jboss_eap_exists.stat.exists == false

  - name: Copy JBoss EAP Patch
    copy:
      src: "{{ jboss_eap_patch_artifact_name }}"
      dest: "{{ jboss_eap_patch_dest }}"
    tags:
      - jboss_eap
    when: transfer_method == 'copy-from-controller' and jboss_eap_apply_patch == true and (jboss_eap_exists.stat.exists == false or 'base' in patch_info_result.stdout)

  - name: Extract JBoss EAP Libraries
    become: true
    unarchive:
      src: "{{ jboss_eap_artifact_dl_dest }}"
      dest: "{{ jboss_eap_library_dest }}"
      creates: jboss-eap-6.4
      copy: no
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
    tags:
      - jboss_eap
    when: jboss_eap_exists.stat.exists == false

# Patches can be applied while EAP is running
  - name: Apply JBoss EAP Patch
    become_user: "{{ jboss_eap_user }}"
    command: "{{ jboss_eap_home }}/bin/jboss-cli.sh 'patch apply {{ jboss_eap_patch_dest }} --verbose'"
#    notify:
#      - Restart jboss-as Service
#      - Verify jboss-as is running
    tags:
      - jboss_eap
      - dev
    when: jboss_eap_apply_patch == true and (jboss_eap_exists.stat.exists == false or 'base' in patch_info_result.stdout)

# TODO edit service file
  - name: Set JBOSS_USER in service script
    lineinfile:
      path: "{{jboss_eap_bin_dir}}/init.d/{{jboss_eap_service_file}}"
      firstmatch: yes
      insertafter: 'CMD_PREFIX='''''
      line: 'JBOSS_USER={{jboss_eap_user}}'

  - name: Set JBOSS_USER in service script
    lineinfile:
      path: "{{jboss_eap_bin_dir}}/init.d/{{jboss_eap_service_file}}"
      firstmatch: yes
      insertafter: 'CMD_PREFIX='''''
      line: 'OLDPWD=~/'

  - name: Create JBos user home directory
    file:
      path: /usr/share/jboss-as
      state: directory

## Copy jboss-as-{{jboss_eap_mode}}.sh or jboss-eap-rhel.sh file to /etc/init.d
  - name: Copy JBoss EAP Service File
    become: true
    copy:
      src: "{{jboss_eap_bin_dir}}/init.d/{{jboss_eap_service_file}}"
      dest: /etc/init.d
      remote_src: True
      owner: "{{ jboss_eap_user }}"
      group: "{{ jboss_eap_group }}"
      mode: "755"
#    notify:
#      - Restart jboss-as Service
#      - Verify jboss-as is running
    tags:
      - jboss_eap

  - name: Add jboss-as Service
    become: true
    command: "chkconfig --add {{jboss_eap_service_file}}"
    tags:
      - jboss_eap

  - name: Enable jboss-as Service
    become: true
    service:
      name: "{{jboss_eap_service_file}}"
      enabled: yes
    tags:
      - jboss_eap

#### Set Sensible Defaults For Runtime

  - name: Set Web Bind Address
    lineinfile:
      dest: "{{ jboss_eap_runtime_conf_file }}"
      line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address={{jboss_eap_bind_web_address}}"
    when: jboss_eap_bind_web_interface
    tags:
      - jboss_eap

  - name: Set Management Bind Address
    lineinfile:
      dest: "{{ jboss_eap_runtime_conf_file }}"
      line: JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address.management={{jboss_eap_bind_management_address}}"
    when: jboss_eap_bind_management_interface
    tags:
      - jboss_eap

  - name: Set User Time Zone for Logs
    lineinfile:
      dest: "{{ jboss_eap_runtime_conf_file }}"
      line: "JAVA_OPTS=\"$JAVA_OPTS -Duser.timezone={{jboss_eap_logging_timezone}}\""
    tags:
      - jboss_eap

  - name: Restart jboss-as Service
    become: true
    service:
      name: "{{ jboss_eap_service_name }}"
      state: restarted
    tags:
      - jboss_eap

  - name: Check jboss-as is available
    uri:
      url: "http://{{jboss_eap_bind_web_address}}:8080"
