ansible_rhel_user: root
eap_java_pkg_name: java-1.8.0-openjdk
transfer_method: copy-from-controller

jboss_java_pkg_name: java-1.8.0-openjdk
install_java: true

jboss_eap_artifact_name: jboss-eap-6.4.0.zip  #jboss-eap-7.2.0.zip #jboss-eap-6.4.0.zip
jboss_eap_patch_artifact_name: jboss-eap-6.4.7-patch.zip #jboss-eap-7.2.1-patch.zip #jboss-eap-6.4.7-patch.zip
jboss_eap_logging_timezone: America/Chicago
jboss_eap_bind_web_interface: true
jboss_eap_bind_management_interface: true
jboss_eap_apply_patch: true

jboss_eap_user: jboss-as

jboss_eap_config: standalone.xml
jboss_eap_mode: standalone
jboss_eap_bind_web_address: 0.0.0.0
jboss_eap_bind_management_address: 0.0.0.0
# Set this value that will suffix jboss-eap in the archive folder e.g. jboss-eap-6.4
jboss_eap_base_version: 6.4
