---
# The group module provides for creating a new user group.
# While a group will be created when a new user is created you should use the
# group modules to customize the group creation.
- name: Create JBoss EAP Group
  become_user: root
  become: true
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "400"

- name: Create JBoss EAP User
  become_user: root
  become: true
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "400"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_library_dest }}"
    shell: "/bin/bash"
